library(testthat)

test_that("Translation works (words from Wikipedia)", {
  expect_equal(pigify("sentence"), "entencesay")
  expect_equal(pigify("pig"), "igpay")
  expect_equal(pigify("latin"), "atinlay")
  expect_equal(pigify("banana"), "ananabay")
  expect_equal(pigify("trash"), "ashtray")
  expect_equal(pigify("happy"), "appyhay")
  expect_equal(pigify("duck"), "uckday")
  expect_equal(pigify("glove"), "oveglay")
  expect_equal(pigify("dopest"), "opestday")
  expect_equal(pigify("me"), "emay")
  expect_equal(pigify("too"), "ootay")
  expect_equal(pigify("will"), "illway")
  expect_equal(pigify("moist"), "oistmay")
  expect_equal(pigify("wet"), "etway")
  expect_equal(pigify("cheers"), "eerschay")
  expect_equal(pigify("shesh"), "eshshay")
  expect_equal(pigify("smile"), "ilesmay")
  expect_equal(pigify("string"), "ingstray")
  expect_equal(pigify("thanks"), "anksthay")
  expect_equal(pigify("stupid"), "upidstay")
  expect_equal(pigify("eat"), "eatay")
  expect_equal(pigify("omelet"), "omeletay")
  expect_equal(pigify("are"), "areay")
  expect_equal(pigify("egg"), "eggay")
})
